Added changes for Network Tokenization
CyberSource/cybersource-rest-client-php pull request #132
Opened 2023-07-31 04:37 UTC by monu-kumar-visa

2023-08-02 10:16 UTC, gnongsie requested changes

2023-08-02 10:16 UTC, gnongsie commented on lib/Authentication/Core/MerchantConfiguration.php
> +        if (isset($config->jwePEMFileDirectory)) {
Shouldn't this be `if (isset($connectionDet->jwePEMFileDirectory)) {` ????

2023-08-02 10:20 UTC, gnongsie approved these changes

2023-09-13 11:33 UTC, gaubansa approved these changes

2023-10-12 09:19 UTC, closed without merging